obj-$(CONFIG_FB_ROCKCHIP) += rk_fb.o rkfb_sysfs.o
obj-$(CONFIG_MFD_RK610) += lcdc/rk30_lcdc.o  
obj-$(CONFIG_LCDC1_RK30) += chips/rk30_lcdc.o  
obj-$(CONFIG_RGA_RK30) += rga/
obj-$(CONFIG_RK_HDMI) += hdmi/
obj-$(CONFIG_HDMI_RK30) += hdmi/
