# Display drivers

display-objs				:= display-sys.o

obj-$(CONFIG_DISPLAY_SUPPORT)		+= display.o
obj-$(CONFIG_DISPLAY_SUPPORT)	    += screen/
obj-$(CONFIG_RK610_LVDS)	    += transmitter/
obj-y								+= lcd/
obj-y								+= tve/